import React from 'react';
import { ArrowRight, Download, Braces, Terminal, GitBranch, CheckCircle2 } from 'lucide-react';
import { PORTFOLIO_DATA } from '../data/portfolioData';
import { GithubIcon, LinkedinIcon } from './SocialIcons';

interface HeroProps { onOpenResume: () => void; onScrollToProjects: () => void; }

export const Hero: React.FC<HeroProps> = ({ onOpenResume, onScrollToProjects }) => (
  <section id="overview" className="relative pt-28 pb-16 lg:pt-36 lg:pb-24 overflow-hidden grid-background">
    <div className="absolute top-1/4 left-10 w-96 h-96 bg-cyan-500/10 rounded-full blur-[120px] pointer-events-none -z-10 animate-pulse-glow" />
    <div className="absolute bottom-10 right-10 w-96 h-96 bg-purple-500/10 rounded-full blur-[120px] pointer-events-none -z-10 animate-pulse-glow" />
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 grid grid-cols-1 lg:grid-cols-12 gap-12 lg:gap-8 items-center">
      <div className="lg:col-span-7 flex flex-col items-start space-y-6">
        <div className="inline-flex items-center gap-2 px-3.5 py-1.5 rounded-full bg-cyan-500/10 border border-cyan-500/30 text-cyan-300 text-xs font-mono font-medium tracking-wide glow-cyan-sm"><span className="w-2 h-2 rounded-full bg-cyan-400 animate-ping" />{PORTFOLIO_DATA.personal.heroBadge}</div>
        <div className="space-y-3"><h1 className="text-4xl sm:text-5xl lg:text-6xl font-extrabold tracking-tight text-white leading-tight">Hi, I'm <span className="gradient-text-cyan-purple">{PORTFOLIO_DATA.personal.name}</span>.</h1><p className="text-2xl sm:text-3xl font-bold tracking-tight text-slate-200 leading-snug">I build <span className="text-cyan-400">useful software</span> with thoughtful <span className="text-purple-400">user experiences</span>.</p></div>
        <p className="text-base sm:text-lg text-slate-400 max-w-2xl leading-relaxed">{PORTFOLIO_DATA.personal.heroDescription}</p>
        <div className="flex flex-wrap items-center gap-4 pt-2"><button onClick={onScrollToProjects} className="px-6 py-3.5 rounded-xl bg-cyan-500 text-[#08090D] font-bold text-sm tracking-wide flex items-center gap-2 hover:bg-cyan-400 transition-all cursor-pointer"><span>View My Projects</span><ArrowRight className="w-4 h-4" /></button><button onClick={onOpenResume} className="px-6 py-3.5 rounded-xl bg-[#101218] hover:bg-[#151821] text-slate-200 font-semibold text-sm border border-[#1F2430] flex items-center gap-2 transition-all cursor-pointer"><Download className="w-4 h-4 text-cyan-400" /><span>View Resume</span></button><div className="flex items-center gap-2 pl-2"><a href={PORTFOLIO_DATA.personal.github} target="_blank" rel="noopener noreferrer" className="p-3 rounded-xl bg-[#101218] border border-[#1F2430] text-slate-400 hover:text-cyan-300" aria-label="GitHub Profile"><GithubIcon className="w-4 h-4" /></a><a href={PORTFOLIO_DATA.personal.linkedin} target="_blank" rel="noopener noreferrer" className="p-3 rounded-xl bg-[#101218] border border-[#1F2430] text-slate-400 hover:text-purple-300" aria-label="LinkedIn Profile"><LinkedinIcon className="w-4 h-4" /></a></div></div>
        <div className="pt-4 border-t border-[#1F2430]/60 w-full flex flex-wrap items-center gap-3 text-xs text-slate-400"><span className="font-mono text-slate-500 uppercase tracking-wider text-[11px]">Core stack:</span>{['React', 'TypeScript', 'JavaScript', 'Python', 'SQL', 'Git'].map((tech) => <span key={tech} className="px-2.5 py-1 rounded-md bg-[#101218] border border-[#1F2430] font-mono text-cyan-300/90 text-[11px]">{tech}</span>)}</div>
      </div>
      <div className="lg:col-span-5 relative"><div className="rounded-2xl bg-[#101218]/90 border border-[#1F2430] p-5 shadow-2xl glass-panel glow-cyan-sm overflow-hidden"><div className="flex items-center gap-2 pb-4 border-b border-[#1F2430]"><span className="w-3 h-3 rounded-full bg-rose-500/80" /><span className="w-3 h-3 rounded-full bg-amber-500/80" /><span className="w-3 h-3 rounded-full bg-emerald-500/80" /><span className="ml-2 text-xs font-mono text-slate-400 flex items-center gap-1.5"><Terminal className="w-3.5 h-3.5 text-cyan-400" />developer_profile.tsx</span></div><div className="mt-5 space-y-4 font-mono text-sm"><div className="text-slate-500">const developer = {'{'}</div><div className="pl-5"><span className="text-purple-300">focus</span>: <span className="text-emerald-300">'frontend &amp; full-stack foundations'</span>,</div><div className="pl-5"><span className="text-purple-300">approach</span>: <span className="text-emerald-300">'learn, build, improve'</span>,</div><div className="pl-5"><span className="text-purple-300">status</span>: <span className="text-cyan-300">'open to opportunities'</span></div><div className="text-slate-500">{'}'}</div></div><div className="grid grid-cols-3 gap-3 mt-6">{[[Braces,'Component-driven'],[GitBranch,'Version control'],[CheckCircle2,'Quality-minded']].map(([Icon,label]) => { const Component = Icon as typeof Braces; return <div key={String(label)} className="p-3 rounded-xl bg-[#151821] border border-[#1F2430] text-center"><Component className="w-4 h-4 text-cyan-400 mx-auto mb-2" /><span className="text-[10px] text-slate-400">{String(label)}</span></div>; })}</div></div></div>
    </div>
  </section>
);
